### ISSUE TITLE
Theme change causing error in temperature display

### ISSUE THREAD

**Issue by engartst** [virag-ky/Weather-Dashboard#22]
If you select *F in the top right and switch themes, the temps all go to *C but *C is still an option to click in the upper right hand. To get back to displaying *F, you currently have to press the temperature button twice instead of it persisting over the theme change.

**Comment by virag-ky** [comment]
Hello,
So basically what it is supposed to do is, by default, when the app starts, the temperature is in Celsius and when you click the F button on top, the temperature should be in Fahrenheit and the button changes to C.

**Comment by virag-ky** [comment]
I see that when the theme changes what it does...
I didn't realize this before.
Thank you for pointing out this. 👍🏻 
I will work on it tomorrow.

**Comment by virag-ky** [comment]
I fixed the issue now, thanks again for letting me know.
